Valnav keyset
Azure-Samples/active-directory-b2c-graph-trustframework-policy pull request #2
Opened 2019-04-04 05:04 UTC by valnav

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2019-04-04 06:27 UTC, parakhj requested changes
Perhaps add more comments or simplify the code a bit :P

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/AuthenticationHelper.cs
> +        public static string[] Scopes = { "User.Read", "Policy.ReadWrite.TrustFramework", "TrustFrameworkKeySet.ReadWrite.All" };
Remove User.Read

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/Constants.cs
>          public const string TrustFrameworkPolicyByIDUri = "https://graph.microsoft.com/testcpimtf/trustFrameworkPolicies/{0}/$value";
Why is this line still here?

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/Program.cs
> +                        request = UserMode.HttpGet(Constants.ResourceUri[uriIndex]);
What's the purpose of doing this?

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/Program.cs
> +            if (resource == "KEYSET")
This is hilarious. It's been a while since you've coded, hasn't it :P

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/Program.cs
> +        public void GetGraphUri()
??

2019-04-04 06:27 UTC, parakhj commented on console-csharp-trustFrameworkPolicy/Program.cs
> +                        request = UserMode.HttpGet(Constants.ResourceUri[uriIndex]);
nvm... figured it out.

2019-04-08 21:41 UTC, valnav commented on console-csharp-trustFrameworkPolicy/AuthenticationHelper.cs
> +        public static string[] Scopes = { "User.Read", "Policy.ReadWrite.TrustFramework", "TrustFrameworkKeySet.ReadWrite.All" };
can i do that later.

2019-04-09 21:13 UTC, valnav commented on console-csharp-trustFrameworkPolicy/Constants.cs
>          public const string TrustFrameworkPolicyByIDUri = "https://graph.microsoft.com/testcpimtf/trustFrameworkPolicies/{0}/$value";
updated

2019-04-09 21:17 UTC, valnav reviewed
made the changes... please review

2019-04-09 21:19 UTC, merged